# Generated by Django 4.1 on 2022-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_todolist_done_alter_todolist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='done',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
